{% set name = "redun" %}
{% set version = "0.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/redun-{{ version }}.tar.gz
  sha256: 7a7f9ac5b48550117ee76eb59855e1f9339197cbc6ed4f7ce373113ca60da027

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - aiobotocore >=2.0.1
    - aiohttp >=3.7.4
    - alembic >=1.4
    - boto3 >=1.16.63
    - botocore >=1.22.8
    - gcsfs >=2021.4.0
    - python >=3.6
    - python-dateutil >=2.8
    - s3fs >=2021.11.1
    - sqlalchemy >=1.3.17,<2

test:
  imports:
    - redun
    - redun.backends
    - redun.executors
  commands:
    - pip check
    - redun --help  # [not win]
  requires:
    - pip

about:
  home: https://insitro.github.io/redun/index.html
  dev_url: https://github.com/insitro/redun/
  summary: Yet another redundant workflow engine.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
