{% set name = "redun" %}
{% set version = "0.25.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/redun-{{ version }}.tar.gz
  sha256: 3f23f8a5571715278ba8485f06b7a5a11fd10e21b5ba1a5292eef491ee31647d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - python >=3.8
    - aiobotocore >=2.0.1
    - aiohttp >=3.7.4,<4
    - alembic >=1.4
    - boto3 >=1.16.63
    - botocore >=1.22.8,!=1.28.0
    - fancycompleter >=0.9.1
    - s3fs >=2021.11.1
    - sqlalchemy >=1.4.0,<2.1
    - python-dateutil >=2.8
    - pyyaml !=6.0.0,!=5.4.0,!=5.4.1
    - requests >=2.27.1
    - rich >=13.3.5
    - textual >=0.63.0

    # Needed for aiobotocore[awscli]
    - awscli >=1.27.76

    # "awscli 2.13.34 has requirement cryptography<40.0.2,>=3.3.2"
    - cryptography <40.0.2,>=3.3.2

    # Upstream script by deafult enables psycopg option
    - psycopg >=2.8

test:
  imports:
    - redun
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://insitro.github.io/redun/index.html
  dev_url: https://github.com/insitro/redun/
  summary: Yet another redundant workflow engine.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
