{% set name = "redun" %}
{% set version = "0.15.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/redun-{{ version }}.tar.gz
  sha256: 9939c4baa41b70837c7265d0e69958eb369414d96fdc031fa31f5b7e5196eb14

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - aiobotocore >=2.0.1
    - aiohttp >=3.7.4,<4
    - alembic >=1.4
    - boto3 >=1.16.63
    - botocore >=1.22.8,!=1.28.0
    - dataclasses >=0.8
    - gcsfs >=2021.4.0
    - python >=3.6
    - python-dateutil >=2.8
    - requests >=2.27.1
    - s3fs >=2021.11.1
    - sqlalchemy >=1.4.0,<2.1
    - types-dataclasses >=0.6.6
    
    # Needed for aiobotocore[awscli]
    - awscli >=1.27.76
    
    # Upstream script by deafult enables psycopg option
    - psycopg >=2.8

test:
  imports:
    - redun
    - redun.backends
    - redun.executors
  commands:
    - pip check
    - redun --help  # [not win]
  requires:
    - pip

about:
  home: https://insitro.github.io/redun/index.html
  dev_url: https://github.com/insitro/redun/
  summary: Yet another redundant workflow engine.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
