schema_version: 1

context:
  name: redun
  version: "0.28.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/redun-${{ version }}.tar.gz
  sha256: 401971c10b2c4777296a7b2b88a30de9ba9c01695c5e11f24e3b7776d271c385

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - aiobotocore >=2.0.1
    - aiohttp >=3.7.4,<4
    - alembic >=1.4
    - boto3 >=1.16.63
    - botocore >=1.22.8,!=1.28.0
    - fancycompleter >=0.9.1
    - s3fs >=2021.11.1
    - sqlalchemy >=1.4.0,<2.1
    - python-dateutil >=2.8
    - pyyaml !=6.0.0,!=5.4.0,!=5.4.1
    - requests >=2.27.1
    - rich >=13.3.5
    - textual >=0.63.0
    # Needed for aiobotocore[awscli]
    - awscli >=1.27.76
    # "awscli 2.13.34 has requirement cryptography<40.0.2,>=3.3.2"
    - cryptography <40.0.2,>=3.3.2
    # Upstream script by deafult enables psycopg option
    - psycopg >=2.8

tests:
  - python:
      imports:
        - redun
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Yet another redundant workflow engine.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://insitro.github.io/redun/index.html
  repository: https://github.com/insitro/redun/

extra:
  recipe-maintainers:
    - thewchan
